### ISSUE TITLE
[client.cc:29] Assertion! Wrong arguments, possible the QP has exsists

### ISSUE THREAD

**Issue by Second222None** [wxdwfc/rlibv2#2]
Hi,
When we run RLibv2 pingong within localhost, everything is OK.
However, when we run RLibv2 pingpong between the host machine and a hosted VM.
It reported the following error:
```
@vm1        [server.cc:20] Pingping server listenes at localhost:8888
@vm1        [server.cc:53] RC pingpong server started!
@localhost  Ok
@localhost  [client.cc:29] Assertion! Wrong arguments, possible the QP has exsists
exit  localhost
@vm1        [server.cc:60] server exit!
@vm1        [rctrl.hh:97] stop with :2 processed.
@vm1
exit  vm1
```

Can anyone give some advice? Thanks in advance.

**Comment by wxdwfc** [comment]
Thank you for your interests. I have not tested your setup. But can you check whether VM-VM works? Besides, how you setup your VM? Does it use SR-IOV?

**Comment by Second222None** [comment]
> Thank you for your interests. I have not tested your setup. But can you check whether VM-VM works? Besides, how you setup your VM? Does it use SR-IOV?

Thanks for your reply! 
First, we created 2 VMs on the same machine by the following command
```
virt-install --virt-type kvm --name vm1 --cpu host --memory 8192 --vcpus 4 --disk ./centos.qcow2,format=qcow2,bus=virtio,size=100 --network network=default,model=virtio --os-type=linux --noautoconsole --boot hd
```
Second, we try to ran Rlibv2 rc_pingpong within a single VM, the same error occurs. And VM-VM doesn't work either.
Third, we suspect that the WrongArg error comes from `ByteBuffer rc_handler(const ByteBuffer &b)`. 
```
if (rc->connect(rc_req.attr) != IOCode::Ok) {
        // in connect error
        RDMA_LOG(4) << "Connect ERROR!";
        registered_qps.dereg(rc_req.name, rc_status.value());
        goto WA;
}
```
Of course, we still need more hints because we're not good at RDMA code.

**Comment by wxdwfc** [comment]
Hi, Thank you for your detailed setup. I've not counted your case but in our setup, but I experienced that using RDMA in a virtual machine needs some extra setup. I've attached our docs on how to do so on a Mellanox ConnectX-4 IB card, which has been tested. 

[Virtualization support for RDMA .pdf](https://github.com/wxdwfc/rlibv2/files/14609854/Virtualization.support.for.RDMA.pdf)

**Comment by wxdwfc** [comment]
Hope it would be helpful.

**Comment by Second222None** [comment]
Thanks! RLibv2 was design to run on IB network,  but our VM use Soft-RoCE network.

**Comment by Second222None** [comment]
Problem solved!
